[[Git]]
arch = "aarch64"
git-tree-sha1 = "248da04dbb3233ea1bf69b4688bdc8b456092200"
os = "macos"

    [[Git.download]]
    sha256 = "82d7e6c82e7fa24599926f27eabaf8c6c898f4661dc34d6ed7c9b34258d6c38f"
    url = "https://github.com/JuliaBinaryWrappers/Git_jll.jl/releases/download/Git-v2.55.0+0/Git.v2.55.0.aarch64-apple-darwin.tar.gz"
[[Git]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "80d6819bb83cf8ec030684e3f8e4087106348842"
libc = "glibc"
os = "linux"

    [[Git.download]]
    sha256 = "89e1b24739d493576f39d27a4963fedbd93c5824f71446f472dffca07dd1b2ec"
    url = "https://github.com/JuliaBinaryWrappers/Git_jll.jl/releases/download/Git-v2.55.0+0/Git.v2.55.0.aarch64-linux-gnu-cxx11.tar.gz"
[[Git]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "ce8810d9a1578fb3aa3e2ba2ea8d68c0125b27c4"
libc = "musl"
os = "linux"

    [[Git.download]]
    sha256 = "1924aa9c91b9b7ae35a7e06f443668f878dc679dee3de6c3c8e2cb637f586de4"
    url = "https://github.com/JuliaBinaryWrappers/Git_jll.jl/releases/download/Git-v2.55.0+0/Git.v2.55.0.aarch64-linux-musl-cxx11.tar.gz"
[[Git]]
arch = "aarch64"
git-tree-sha1 = "1d1fd9780780c2b6ffd42a3c031bf951afc69dc1"
os = "freebsd"

    [[Git.download]]
    sha256 = "b8de9251d34667fdaaed6e271b38832ca9a43ff102bcfd9b47101f0d79dbc3ce"
    url = "https://github.com/JuliaBinaryWrappers/Git_jll.jl/releases/download/Git-v2.55.0+0/Git.v2.55.0.aarch64-unknown-freebsd.tar.gz"
[[Git]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "a76c5c1c04ed50ffdd34b842c4eeef6e9848d391"
libc = "glibc"
os = "linux"

    [[Git.download]]
    sha256 = "9fc6472ba3b2049ada4c442120ea991a4fd7c1eefda45b89c9e23c059480fc34"
    url = "https://github.com/JuliaBinaryWrappers/Git_jll.jl/releases/download/Git-v2.55.0+0/Git.v2.55.0.armv6l-linux-gnueabihf-cxx11.tar.gz"
[[Git]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "3c96830c04870fd59ed3a9aac0db222a1d1bcb1c"
libc = "musl"
os = "linux"

    [[Git.download]]
    sha256 = "1210c6aeed6a56de8ec6f688dca915d88a3e7242f0aa075eb7d712ea7a661afb"
    url = "https://github.com/JuliaBinaryWrappers/Git_jll.jl/releases/download/Git-v2.55.0+0/Git.v2.55.0.armv6l-linux-musleabihf-cxx11.tar.gz"
[[Git]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "f2dd0ab69af0e5a686c6fe94276d61c8a2d85307"
libc = "glibc"
os = "linux"

    [[Git.download]]
    sha256 = "85865e489de3d3ea67413eba18e09d034e087a83bce75207ca700eff32dc3e05"
    url = "https://github.com/JuliaBinaryWrappers/Git_jll.jl/releases/download/Git-v2.55.0+0/Git.v2.55.0.armv7l-linux-gnueabihf-cxx11.tar.gz"
[[Git]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "bde2e2393905851878b753f6502d43e3202f8a23"
libc = "musl"
os = "linux"

    [[Git.download]]
    sha256 = "42875de2f4b48d3f0abda9652159a269683b2eac47ec1abbef9928e361dcd1bb"
    url = "https://github.com/JuliaBinaryWrappers/Git_jll.jl/releases/download/Git-v2.55.0+0/Git.v2.55.0.armv7l-linux-musleabihf-cxx11.tar.gz"
[[Git]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "aa8951965f6298e68a865059edef704fb81ac90e"
libc = "glibc"
os = "linux"

    [[Git.download]]
    sha256 = "0cee8e452fe476eb32a15314c0c8691d3e9fd37d41d74fda9f6a6485c6bcc0aa"
    url = "https://github.com/JuliaBinaryWrappers/Git_jll.jl/releases/download/Git-v2.55.0+0/Git.v2.55.0.i686-linux-gnu-cxx11.tar.gz"
[[Git]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "60cc486a0126aeec3d159afd9cb8ffa1a735ab62"
libc = "musl"
os = "linux"

    [[Git.download]]
    sha256 = "f7ee2c3c6cf58e00426282f73f2cd3c6e9d26f38e05d9ffcbc4c2829c5461aa9"
    url = "https://github.com/JuliaBinaryWrappers/Git_jll.jl/releases/download/Git-v2.55.0+0/Git.v2.55.0.i686-linux-musl-cxx11.tar.gz"
[[Git]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "fd6c4044ca3c003b50d6e7c9450e80264ba15a05"
os = "windows"

    [[Git.download]]
    sha256 = "91a0369b3458172d63a1004b92c84987c0adc01bc7db5100461acc7f37fc4ba8"
    url = "https://github.com/JuliaBinaryWrappers/Git_jll.jl/releases/download/Git-v2.55.0+0/Git.v2.55.0.i686-w64-mingw32-cxx11.tar.gz"
[[Git]]
arch = "powerpc64le"
cxxstring_abi = "cxx11"
git-tree-sha1 = "2754bbc7b61df2ec0ee394d5aa679c9212f910a2"
libc = "glibc"
os = "linux"

    [[Git.download]]
    sha256 = "0db720dd62c157fe301fb5233a6fee23efdd8d70be3490e2ebf61ae26c0f7e23"
    url = "https://github.com/JuliaBinaryWrappers/Git_jll.jl/releases/download/Git-v2.55.0+0/Git.v2.55.0.powerpc64le-linux-gnu-cxx11.tar.gz"
[[Git]]
arch = "riscv64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "91106a6dcba6ec0747f29381f7ff826e72ed5e27"
libc = "glibc"
os = "linux"

    [[Git.download]]
    sha256 = "f4ed9c840cb5d653f9f927790449dc2b8a4c014bc542e37880c445f40ffda972"
    url = "https://github.com/JuliaBinaryWrappers/Git_jll.jl/releases/download/Git-v2.55.0+0/Git.v2.55.0.riscv64-linux-gnu-cxx11.tar.gz"
[[Git]]
arch = "x86_64"
git-tree-sha1 = "96f28d9f8ac533bf1eff8c7953d2b8f755d8e52f"
os = "macos"

    [[Git.download]]
    sha256 = "dbde8d95715344b38d546a9144bbf27a1d3ba4a7dbbf888692d1e122d3778baf"
    url = "https://github.com/JuliaBinaryWrappers/Git_jll.jl/releases/download/Git-v2.55.0+0/Git.v2.55.0.x86_64-apple-darwin.tar.gz"
[[Git]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "3f4122d832fb26a4b850eb4882c813111acf1817"
libc = "glibc"
os = "linux"

    [[Git.download]]
    sha256 = "2cbcd860d34eb8a0e2ea7bd4fee2193788fe11a746a4d6746fb668a1ee6607bd"
    url = "https://github.com/JuliaBinaryWrappers/Git_jll.jl/releases/download/Git-v2.55.0+0/Git.v2.55.0.x86_64-linux-gnu-cxx11.tar.gz"
[[Git]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "c70a6120b254b73f15539419931e5721703f46cf"
libc = "musl"
os = "linux"

    [[Git.download]]
    sha256 = "29977d83813942e5516b259b3460f3420e12e8880e04d0079538daa0d51eac5a"
    url = "https://github.com/JuliaBinaryWrappers/Git_jll.jl/releases/download/Git-v2.55.0+0/Git.v2.55.0.x86_64-linux-musl-cxx11.tar.gz"
[[Git]]
arch = "x86_64"
git-tree-sha1 = "809f55a48211bb703df70cf2f348ea2b10253bb6"
os = "freebsd"

    [[Git.download]]
    sha256 = "2d760044b020aac65753d30a65413729a5ebebbf924ea76eabbe477bbf687982"
    url = "https://github.com/JuliaBinaryWrappers/Git_jll.jl/releases/download/Git-v2.55.0+0/Git.v2.55.0.x86_64-unknown-freebsd.tar.gz"
[[Git]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "6ea079b340defe123b59e16743cacb80c09eecfb"
os = "windows"

    [[Git.download]]
    sha256 = "6d350a757a70248839eb4d8c9b513c90527d56d48eb7d729f0d8d2815a5d9e76"
    url = "https://github.com/JuliaBinaryWrappers/Git_jll.jl/releases/download/Git-v2.55.0+0/Git.v2.55.0.x86_64-w64-mingw32-cxx11.tar.gz"
